apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: watchman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant
        ports:
        - containerPort: 6333
        - containerPort: 6334
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
        readinessProbe:
          tcpSocket:
            port: 6333
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6333
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: watchman
spec:
  selector:
    app: qdrant
  ports:
  - name: api
    port: 6333
    targetPort: 6333
  - name: grpc
    port: 6334
    targetPort: 6334
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: watchman
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi